#!/bin/bash
# Get mining status and generate status report
# Run this script on the VPS as root

set -e

MINER_DIR="/root/midnight-miner"
WALLETS_FILE="$MINER_DIR/wallets.json"
CHALLENGES_FILE="$MINER_DIR/challenges.json"

echo "# Mining Status Report"
echo ""
echo "**Generated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
echo "**Hostname:** $(hostname)"
echo ""

# Service status
echo "## Service Status"
echo ""
if systemctl is-active --quiet midnight-miner; then
    echo "**Status:** Running ✅"
    export UPTIME=$(systemctl show midnight-miner --property=ActiveEnterTimestamp --value)
    echo "**Started:** $UPTIME"
    SERVICE_RUNNING=true
else
    echo "**Status:** Stopped ❌"
    SERVICE_RUNNING=false
fi
echo ""

# Hash rate from recent logs
echo "## Mining Performance"
echo ""
LAST_HASHRATE=$(journalctl -u midnight-miner -n 100 | grep "Total Hash Rate" | tail -1 | awk '{print $NF}')
if [ -n "$LAST_HASHRATE" ]; then
    echo "**Hash Rate:** $LAST_HASHRATE"
else
    echo "**Hash Rate:** N/A"
fi
echo ""

# Solutions count (from miner's Total Completed counter - same as check command)
if [ "$SERVICE_RUNNING" = true ]; then
    SOLUTIONS_COUNT=$(journalctl -u midnight-miner -n 100 --no-pager | grep "Total Completed" | tail -1 | awk '{print $8}' || echo "0")
else
    SOLUTIONS_COUNT="0"
fi
echo "**Total Solutions:** $SOLUTIONS_COUNT"
echo ""

# Wallets information
echo "## Wallets"
echo ""
if [ -f "$WALLETS_FILE" ]; then
    WALLET_COUNT=$(python3 -c "import json; data=json.load(open('$WALLETS_FILE')); print(len(data))" 2>/dev/null || echo "0")
    echo "**Total Wallets:** $WALLET_COUNT"
    echo ""

    # Solutions per wallet
    echo "### Solutions per Wallet"
    echo ""
    echo "| Wallet | Address | Solutions | Verify |"
    echo "|--------|---------|-----------|--------|"

    python3 << PYEOF
import json
import subprocess

# Load wallets and challenges to get accurate solution counts
try:
    with open('/root/midnight-miner/wallets.json') as f:
        wallets = json.load(f)

    with open('/root/midnight-miner/challenges.json') as f:
        challenges = json.load(f)

    # Count solutions per wallet from challenges.json (persistent storage)
    wallet_solutions = {}
    for challenge_data in challenges.values():
        solved_by = challenge_data.get('solved_by', [])
        for addr in solved_by:
            wallet_solutions[addr] = wallet_solutions.get(addr, 0) + 1

    for i, wallet in enumerate(wallets):
        addr = wallet['address']
        solution_count = wallet_solutions.get(addr, 0)

        # Create verification link
        verify_link = f"[API](https://sm.midnight.gd/api/statistics/{addr})"

        print(f"| {i+1} | {addr[:20]}... | {solution_count} | {verify_link} |")

except Exception as e:
    print(f"Error loading wallet/challenge data: {e}")
PYEOF
else
    echo "No wallets file found"
fi
echo ""

# Recent solutions (from all logs)
echo "## Recent Solutions (Last 10)"
echo ""
if [ "$SERVICE_RUNNING" = true ]; then
    RECENT_SOLUTIONS=$(journalctl -u midnight-miner | grep "Solution accepted" | tail -10)
else
    RECENT_SOLUTIONS=""
fi

if [ -n "$RECENT_SOLUTIONS" ]; then
    echo '```'
    echo "$RECENT_SOLUTIONS"
    echo '```'
else
    echo "No solutions found yet"
fi
echo ""

# Challenge information
echo "## Challenges"
echo ""
if [ -f "$CHALLENGES_FILE" ]; then
    python3 -c "
import json
from datetime import datetime, timezone

with open('/root/midnight-miner/challenges.json') as f:
    challenges = json.load(f)

print(f'**Total Challenges Discovered:** {len(challenges)}')
print()
print('| Challenge ID | Difficulty | Deadline |')
print('|--------------|-----------|----------|')

for cid, data in sorted(challenges.items()):
    deadline = data['latest_submission']
    diff = data['difficulty'][:8]
    print(f'| {cid} | {diff} | {deadline} |')
" 2>/dev/null || echo "Error reading challenges"
else
    echo "No challenges file found"
fi
echo ""

# System resources
echo "## System Resources"
echo ""
echo "**CPU Usage:**"
echo '```'
top -bn1 | grep "Cpu(s)" | head -1
echo '```'
echo ""
echo "**Memory Usage:**"
echo '```'
free -h | grep -E "Mem|Swap"
echo '```'
echo ""

echo "---"
echo "*Report generated by midnight-miner*"
