#!/bin/bash
#
# Local Mining Status Report Generator
# Generates a markdown status report for local mining instance
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

PID_FILE=".miner.pid"
LOG_FILE="miner.log"

echo "# Midnight Miner - Local Status Report"
echo ""
echo "**Generated:** $(date '+%Y-%m-%d %H:%M:%S %Z')"
echo ""

# Process Status
echo "## Process Status"
echo ""
if [ -f "$PID_FILE" ] && kill -0 $(cat "$PID_FILE") 2>/dev/null; then
    PID=$(cat "$PID_FILE")
    echo "- **Status:** Running"
    echo "- **PID:** $PID"

    # Get process info
    if command -v ps &> /dev/null; then
        CPU=$(ps -p $PID -o %cpu= 2>/dev/null || echo "N/A")
        MEM=$(ps -p $PID -o %mem= 2>/dev/null || echo "N/A")
        ELAPSED=$(ps -p $PID -o etime= 2>/dev/null || echo "N/A")
        echo "- **CPU Usage:** ${CPU}%"
        echo "- **Memory Usage:** ${MEM}%"
        echo "- **Uptime:** $ELAPSED"
    fi
else
    echo "- **Status:** Stopped"
    rm -f "$PID_FILE" 2>/dev/null
fi
echo ""

# Wallet Status
echo "## Wallet Status"
echo ""
if [ -f "wallets.json" ]; then
    WALLET_COUNT=$(python3 -c "import json; print(len(json.load(open('wallets.json'))))" 2>/dev/null || echo "0")
    echo "- **Wallets Loaded:** $WALLET_COUNT"

    # Show first 3 wallet addresses
    if [ "$WALLET_COUNT" -gt 0 ]; then
        echo ""
        echo "### Sample Addresses"
        echo ""
        python3 << 'EOF'
import json
try:
    with open('wallets.json', 'r') as f:
        wallets = json.load(f)
    for i, wallet in enumerate(wallets[:3]):
        addr = wallet.get('address', 'N/A')
        print(f"{i+1}. `{addr[:20]}...{addr[-10:]}`")
    if len(wallets) > 3:
        print(f"... and {len(wallets) - 3} more")
except Exception as e:
    print(f"Error reading wallets: {e}")
EOF
    fi
else
    echo "- **Wallets:** None (will be generated on first run)"
fi
echo ""

# Mining Performance
echo "## Mining Performance"
echo ""
if [ -f "$LOG_FILE" ]; then
    # Extract hash rate if available
    HASH_RATE=$(tail -n 100 "$LOG_FILE" | grep -oP '\d+\.\d+ KH/s' | tail -1 || echo "N/A")
    echo "- **Current Hash Rate:** $HASH_RATE"

    # Count solutions submitted
    SOLUTIONS=$(grep -c "Solution submitted" "$LOG_FILE" 2>/dev/null || echo "0")
    echo "- **Solutions Submitted:** $SOLUTIONS"

    # Count challenges discovered
    CHALLENGES=$(grep -c "New challenge discovered" "$LOG_FILE" 2>/dev/null || echo "0")
    echo "- **Challenges Discovered:** $CHALLENGES"
else
    echo "- **Hash Rate:** N/A (no logs)"
    echo "- **Solutions:** N/A"
    echo "- **Challenges:** N/A"
fi
echo ""

# Recent Activity
echo "## Recent Activity"
echo ""
if [ -f "$LOG_FILE" ]; then
    echo '```'
    tail -n 15 "$LOG_FILE"
    echo '```'
else
    echo "No activity logs found."
fi
echo ""

# System Resources
echo "## System Resources"
echo ""
if command -v nproc &> /dev/null; then
    CPUS=$(nproc)
    echo "- **CPU Cores:** $CPUS"
fi

if command -v free &> /dev/null; then
    TOTAL_MEM=$(free -h | awk '/^Mem:/ {print $2}')
    USED_MEM=$(free -h | awk '/^Mem:/ {print $3}')
    echo "- **Memory:** $USED_MEM / $TOTAL_MEM used"
fi

if command -v uptime &> /dev/null; then
    LOAD=$(uptime | awk -F'load average:' '{print $2}')
    echo "- **Load Average:**$LOAD"
fi
echo ""

# File Locations
echo "## Files"
echo ""
echo "- **Wallets:** \`wallets.json\`"
echo "- **Logs:** \`$LOG_FILE\`"
echo "- **PID File:** \`$PID_FILE\`"
echo "- **Config:** \`config/local.conf\`"
echo ""

echo "---"
echo "*Generated by Midnight Miner*"
